[package]
name = "cpu-count"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = "1"
# neon = {version = "0.10.1", default-features = false, features = ["napi-6", "promise-api", "task-api"]}
